belief_threshold: 0.8

#search_terms:
#- "search term 1"
#- "search term 2"

search_genes:
- HMOX1
- SLC2A2
- IGF2
- FOXO1
- ENO1
- IAPP
- SOS2
- HSF1
- IRS4
- IL1B
- SHC1
- IDE
- CSNK2A3
- ADAM10
- IGF1R
- ADD3
- IGF1
- NGFR
- GLB1
- PIK3R5
- IL34
- IRS1
- ISL1
- HPSE
- GSK3A
- MME
- GSK3B
- SLC2A4
- PCK1
- CHAT
- IL6
- ACHE
- IL4
- PIK3R1
- TNF
- PDX1
- SLC2A8
- GCG
- STAR
- ACACA
- FOXO3
- SHC2
- RPS6KB1
- AKT1
- ENPP1
- RAF1
- PPP1R3A
- CAMK2A
- OGT
- CAPN1
- HK2
- ADIPOQ
- HEXB
- CALHM1
- GRIN1
- INPPL1
- BCHE
- INS
- PDK1
- IGFBP2
- IRS2
- MAPT
- HSPA1B
- TTR
- PPARG
- PPP2CA
- APOE
- APP
- SHC3
- ALB
- POMC
- SHC4
- CDK5R1
- MAPK8
- ECE1
- BACE1
- SORCS1
- PDPK1
- GRB2
- INSR
