belief_threshold: 0.8

ndex:
  name: "Fanconi Anemia Machine"
  network: e70090bc-47a5-11e8-a935-0ac135e8bacf

search_terms_num_days: 5

search_terms:
- "Fanconi Anemia"

search_genes:
- FANCA
- FANCB
- FANCC
- BRCA2
- FANCD2
- FANCE
- FANCF
- FANCG
- FANCI
- BRIP1
- FANCL
- FANCM
- PALB2
- RAD51C
- SLX4
- ERCC4
- RAD51
- BRCA1
- UBE2T
- XRCC2
