belief_threshold: 0.5

ndex:
  name: "Anxiety"
  network: b69c04be-38c9-11e8-8695-0ac135e8bacf

search_terms_num_days: 1

search_terms:
- Anxiety
- stress
- Aggression
- Depression
#- response

#search_chemicals:
- dopamine
- serotonin

search_genes:
- GRIN2D
- CRHR1
- HTR1A
- PDYN
- PITX3

