belief_threshold: 0.8

ndex:
  name: "Anxiety"

search_terms:
- Anxiety
- stress
- Aggression
- Depression
#- response

#search_chemicals:
- dopamine
- serotonin

search_genes:
- GRIN2D
- CRHR1
- HTR1A
- PDYN
- PITX3

