belief_threshold: 0.8

ndex:
  name: "Alzheimer's Disease - Tau Subgraph"

search_terms:
- tau

search_genes:
- CHI3L1
- PPP3CA
- CDKN1A
- NEFL
- CTNNB1
- MAPK14
- CASP4
- CCL2
- SNCA
- CRH
- NPEPPS
- DYRK1A
- FRAT2
- CDK5
- KLF10
- IGF1
- MAPK11
- GRK5
- GSK3A
- PPP5C
- GSK3B
- CHAT
- IL6
- MAPK1
- MIR16-1
- TIMP1
- PDHA1
- PPP1R1B
- KLC1
- KLF1
- CDKN1B
- LEP
- MIR132
- GCG
- MAPK9
- PRKAR1A
- PIN1
- PKN1
- RPS6KB1
- AKT1
- DKK1
- S100B
- CDC37
- CAMK2A
- MIR15A
- OGT
- TPPP
- CAPN1
- CDK2
- YWHAZ
- GRK2
- PRKACA
- F2
- AKAP13
- GAL
- INS
- JUN
- CAST
- HSPA4
- PPP2CB
- WNT3A
- MAPT
- MAPK10
- HSPA1B
- PRKACG
- PPP2CA
- BAG1
- RB1
- PHF1
- PTPA
- APP
- CASP3
- EGR1
- ABL1
- POMC
- MAPK3
- EIF2AK2
- TPK1
- CDK5R1
- MAPK8
- NAB2
- ATF2
- CAMK2B