belief_threshold: 0.8

#search_terms:
#- "search term 1"
#- "search term 2"

search_genes:
- TRAF6
- NEFL
- CCL2
- MSR1
- IRAK1
- S100A9
- MIR107
- PTX3
- MIR146A
- COL3A1
- NOS2
- TNF
- CD86
- IL23A
- CSF1
- KEAP1
- MYD88
- PPARA
- ADIPOQ
- LAMC2
- NGF
- CHRNB2
- VTN
- PPARG
- SDC1
- IL1A
- NFE2L2
- COL1A1
- CHI3L1
- PTGS2
- MRC1
- MAPK14
- CD200R1
- NRGN
- LCK
- IL6
- TREM1
- TREM2
- SCARF1
- MT-CO2
- TSPAN12
- DDX39B
- IL12B
- CHRNA3
- CFH
- S100B
- CD80
- MIR34A
- IRAK2
- CCR7
- CD14
- EIF2AK2
- ALOX5
- PLA2G4A
- ITGB3
- MPO
- LAMC1
- IL1B
- ANXA1
- OSM
- SCARB1
- CD28
- IL13
- GSK3B
- BDNF
- MIR659
- CD200
- LAMB2
- NFKB2
- MAPK1
- FPR1
- THBS3
- IL18
- IL33
- CHRNA7
- MIR590
- FPR2
- PAFAH2
- EDN1
- SCARA5
- DDIT3
- PLA2G7
- MAPT
- IL4R
- MIR155
- APP
- ITGA5
- ICAM1
- NOD2
- CHRNA4
- CD44
- TLR4
- STAT3
- NFKB1
- AGO2
- AGER
- SPP1
- GRN
- TLR2
- CHRNA5
- ARG1
- MOK
- PTPN11
- IL10
- IL2RA
- IFNG
- IL5
- PTGS1
- IL4
