belief_threshold: 0.8

ndex:
  name: "Anhedonia"
  network: b628d08c-38c9-11e8-8695-0ac135e8bacf

search_terms_num_days: 1

search_terms:
- Anhedonia
- motivation
- drive
- stress

#search_chemicals:
- dopamine

search_genes:
- CACNA1C
- SETDB1
- DISC1
- CRHR1
- COMT
- KCNK2
- ANK3
- OPRK1
- PDYN
- PITX3
