belief_threshold: 0.8

search_terms_number_days: 7

ndex:
  name: "Alzheimer's Disease - TREM2 and CD33 Signaling"
  network: 662d76d3-2deb-11e8-b939-0ac135e8bacf

search_terms:
- "inflammation"
- "microglia"

search_genes:
- TREM2
- CD33
- MIF
- VEGF
- C3
- CCL2

- VEGFR
- Il6
- Il8
- MCP1
- CRP
- ICAM1
- VCAM1
- C1QBP
- MCP1
- CXCL10
- IP10
- IL1RAP
