belief_threshold: 0.8

ndex:
  name: "Alzheimer's Disease - DKK1 Subgraph"
  network: 12d4ae3c-38c9-11e8-8695-0ac135e8bacf

search_terms:
- "WNT signaling"

search_genes:
- BACE1
- GSK3B
- MAPT
- FOS
- DKK1
- NEFH
- AKT1
- DKK4
- MAP2
- APP
- EGR1
- NAB2
- KLF10
- TP53
- DKK2
- DKK3
- CLU
- WNT3A